services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    command: sh -c "yarn start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    # volumes:
    #   - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: headlines

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: headlines

volumes:
  todo-mysql-data:
