services:
  playwright-app-1:
    build:
      context: ./playwright
      dockerfile: Dockerfile
    command: sh -c "yarn start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    # volumes:
    #   - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: headlines
      MYSQL_TABLE: Another_Debate_2024
      SEARCH_TERM: trump harris second debate

  playwright-app-2:
    build:
      context: ./playwright
      dockerfile: Dockerfile
    command: sh -c "yarn start"
    ports:
      - 127.0.0.1:3001:3000
    working_dir: /app
    # volumes:
    #   - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: headlines
      MYSQL_TABLE: Israel_Hez_Oct
      SEARCH_TERM: israel hezbolloh
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "yarn start"
    ports:
      - 127.0.0.1:3002:3000
    working_dir: /app
    # volumes:
    #   - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: headlines
      MYSQL_TABLE: Another_Debate_2024
      SEARCH_TERM: trump harris second debate
     
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: headlines

volumes:
  todo-mysql-data:
